import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Load Roboto font
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // যেসব weight লাগবে সেগুলো রাখো
});

export const metadata: Metadata = {
  title: "Create Deshit BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-white text-gray-900`}>
        <div className="min-h-screen flex flex-col">
          {/* Header / Navbar future e ekhane add kora jabe */}
          <main className="flex-1">{children}</main>
          {/* Footer future e ekhane add kora jabe */}
        </div>
      </body>
    </html>
  );
}
